//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstrumentShop.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrument()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> PricePerItem { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<int> QuantityLeft { get; set; }
        public string Condition { get; set; }
        public string Tuning { get; set; }
        public string NumberOfStrings { get; set; }
        public string Mouthpiece { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
