//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstrumentShop.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> PricePerItem { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<int> QuantityLeft { get; set; }
        public string Condition { get; set; }
        public string BusinessSpecificDetail { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
