//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtGallery.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int ID { get; set; }
        public int ArtistID { get; set; }
        public string WorkType { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Value { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Height { get; set; }
        public string Type { get; set; }
        public Nullable<float> Weight { get; set; }
        public string Material { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
